services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src        # Seulement le code source est necessaire pour le dev en hot reload, er eventuellement le pom.xml aussi pour les dependnace si j'en ajoute au fur et a mesure
      - ./backend/pom.xml:/app/pom.xml
      # - ./backend/.mvn:/app/.mvn    #sinon deadlock
      # - ./backend/mvnw:/app/mvnw
    #command: sh -c "ls -l .mvn/wrapper && cat .mvn/wrapper/maven-wrapper.properties && ./mvnw spring-boot:run -Dspring-boot.run.fork=false"
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    command: npm run dev -- --host